#!/bin/bash
 ___ _       _                     ___   _______    
|_ _| |_ ___| |    ___  __ _  __ _| \ \ / /_   _|   
 | || __/ __| |   / _ \/ _` |/ _` | |\ V /  | |     
 | || |_\__ \ |__|  __/ (_| | (_| | | | |   | |     
|___|\__|___/_____\___|\__, |\__,_|_| |_|   |_|____ 
                       |___/                 |_____|

git clone https://github.com/achul123/skyportd.git
cd skyportd 
npm install

echo_message "* cd skyportd"

echo_message "* paste your configure code"

echo_message "* pm2 start ."
